apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: global
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: keyvault-federated-identity-sa
        namespace: external-secrets
      vaultUrl: https://kv-frst-gen-test-aks-001.vault.azure.net/
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: emetsa-nonprod
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: keyvault-federated-identity-sa
        namespace: external-secrets
      vaultUrl: https://kv-emetsa-devtest-001.vault.azure.net/
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: minskog-nonprod
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: keyvault-federated-identity-sa
        namespace: external-secrets
      vaultUrl: https://kv-minskog-devtest-001.vault.azure.net/